### ISSUE TITLE
Tag name for PHONE field not changing from {name_3} to {phone}

### ISSUE THREAD

**Issue by YuryKomar** [witsec/mobirise-mailform#2]
When I want to see the phone number from the form filed named PHONE, when sending the form, then I receive empty data, but if I use filed name {name_3}, the number passed to the filed is received normlly.

So, the filed name is {PHONE}, but actually it is under the filed name {name_3} (the bug).

Below is the form template I use, but want to change the {name_3} to {phone}.
=========================================
{message}
---
Name: {name}
Mail: {email}
Phone: {name_3}
Age: {babyage}
_________________________
Date (UTC+2): {date}
=========================================

Please fix it.

**Comment by witsec** [comment]
Hi Yury, what version are you on and what block are you using? The normal contact form block of the 'builder' block?

**Comment by YuryKomar** [comment]
Hi, I am usin buider block to add another field to the form.
The version is latest 12.1, just checked now, same problem.

**Comment by witsec** [comment]
There haven't been any updates on this issue, so I'm closing it. If there's still an issue, please reopen.
