### ISSUE TITLE
Custom form styling issue

### ISSUE THREAD

**Issue by qerelt** [witsec/mobirise-mailform#3]
Custom form elements such as buttons are not conforming to the general website styling

**Comment by witsec** [comment]
I'm not sure what you mean. When I change the primary color of a website, it reflects that in the button.

What theme are you using? Could you show some examples, with screenshots or perhaps a (published) website somewhere? Thanks.

**Comment by qerelt** [comment]
Hello, sorry for not being specific.
I used M5 template and because the custom form extension styling did not work, I left it out when publishing.
Will send your way if it ever comes up again.
